name: Service Now Request Management
description: Modifies Service Now Requests
inputs:
  action-version:
    type: string
    title: Action Version
    description: The version of the action to use
    required: true
  github-token:
    type: string
    title: GitHub Token
    description: The GitHub token to use for authentication
    required: true
  sn-base-url:
    type: string
    title: Service Now Base URL
    description: The base URL of the Service Now instance
    required: true
  sn-username:
    type: string
    title: Service Now Username
    description: The username to use for authentication
    required: true
  sn-password:
    type: string
    title: Service Now Password
    description: The password to use for authentication
    required: true
  sn-request-id:
    type: string
    title: Service Now Request ID
    description: The ID of the Service Now request to modify
    required: true
  sn-action:
    type: string
    title: Service Now Action
    description: The action to perform on the Service Now request
    required: true
    enum:
      - add_comment
      - add_work_notes
      - close_request
      - update_request_variable

  # Usage:
  # The inputs to use for the Service Now action. The inputs are
  # different for each action. Use the following as a guide -
  # * add_comment - `my comment`
  # * add_work_notes - `my work note`
  # * close_request - ``
  # * update_request_variable - `my_variable` and `my value`

  sn-input1:
    type: string
    title: Service Now Input 1
    description: The first input to the Service Now action
    required: true
  sn-input2:
    type: string
    title: Service Now Input 2
    description: The second input to the Service Now action (optional)
    required: false

outputs:
  output:
    type: string
    title: Output
    description: Output from the Service Now action script
    value: ${{ steps.run-service-now-action.outputs.output }}

runs:
  using: composite
  steps:
    - name: Checkout actions repo
      uses: actions/checkout@v4
      with:
        repository: tamu-edu/it-ae-actions-servicenow
        path: action
        ref: ${{ inputs.action-version }}
        token: ${{ inputs.github-token }}

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install python dependencies
      run: pip install -r ./action/python/requirements.txt

    - name: run-service-now-action
      shell: bash
      env:
        SN_BASE_URL: ${{ inputs.sn-base-url }}
        SN_USERNAME: ${{ inputs.sn-username }}
        SN_PASSWORD: ${{ inputs.sn-password }}
      run: |
        ARGS="--request_id ${{ inputs.sn-request-id }}"
        if [[ "${{ inputs.sn-action }}" == "add_comment" ]]; then
          ARGS="${ARGS} add_comment --comment '${{ inputs.sn-input1 }}"
        elif [[ "${{ inputs.sn-action }}" == "add_work_notes" ]]; then
          ARGS="${ARGS} add_work_notes --work_notes '${{ inputs.sn-input1 }}'"
        elif [[ "${{ inputs.sn-action }}" == "update_request_variable" ]]; then
          ARGS="${ARGS} update_request_variable --variable_name ${{ inputs.sn-input1 }} --variable_value '${{ inputs.sn-input2 }}'"
        else
          echo "Invalid action: '${{ inputs.sn-action }}'"
          exit 1
        fi

        echo "ARGS: ${ARGS}"

        python ./action/python/service_now_updater.py ${ARGS} 2>&1 | tee /tmp/output.txt
        echo "output<<EOF" >> $GITHUB_OUTPUT
        cat /tmp/output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

